import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "GEAR UP",
  icons: {
    icon: "/logo.png",
  },
  description: "Generated by create Gear Up",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", "font-sans")}
    >
      <body className="min-h-full w-full flex flex-col">
            {children}
      </body>
    </html>
  );
}
